# src/monitoring/metrics.py
"""
System monitoring and metrics logging for the MathRAG-Gate project.

This module provides utilities to log system behavior, which is crucial for
debugging, auditing, and future system improvements.

FIX: Added explicit type casting (bool(), float()) to handle NumPy types 
that are not natively JSON serializable.
"""

import json
from datetime import datetime
import os
import logging
from src.config import settings

# Initialize logger for error handling
logger = logging.getLogger(__name__)

class SystemMetrics:
    """
    A class to log system metrics and decisions to a file.
    
    Attributes:
        log_file (str): The path to the log file (JSONL format).
    """
    
    def __init__(self):
        """Initializes the SystemMetrics logger and creates the results directory."""
        # Ensure the results directory exists
        os.makedirs(settings.RESULTS_DIR, exist_ok=True)
        self.log_file = os.path.join(settings.RESULTS_DIR, "metrics.jsonl")

    def log_query(self, query: str, method: str, latency: float, use_rule: bool, quality_score: float, response: str):
        """
        Logs a single query event to the metrics log file.
        
        The log is in JSONL format (one JSON object per line), which is easy to parse later.
        
        Args:
            query (str): The user's original question.
            method (str): The retrieval method used (e.g., "MathRAG-Gate").
            latency (float): The time taken to process the query (in seconds).
            use_rule (bool): Whether the rule-based RQP was used.
            quality_score (float): The quality score of the top retrieved document.
            response (str): The final answer generated by the LLM.
        """
        # Create a structured log entry
        # [CRITICAL FIX] Explicitly cast values to Python native types.
        # This prevents "TypeError: Object of type bool_ is not JSON serializable"
        # when passing numpy/scipy results directly to json.dumps.
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "query": query,
            "method": method,
            "latency": float(latency),          # Cast numpy.float to float
            "use_rule": bool(use_rule),         # Cast numpy.bool_ to bool
            "quality_score": float(quality_score), # Cast numpy.float to float
            "response": str(response)           # Ensure string format
        }
        
        # Append the log entry to the file safely
        try:
            with open(self.log_file, "a", encoding="utf-8") as f:
                f.write(json.dumps(log_entry, ensure_ascii=False) + "\n")
        except Exception as e:
            # If logging fails, print error but don't crash the main program
            logger.error(f"Failed to write metrics log: {e}")